format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/atmosphere/restart_dump.astart
  hashes:
    binhash: b0e3194188cf32d64527f59eca1ddd40
    md5: cc70609054bade71d4a7fd1ee1365090
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/atmosphere/um.res.yaml
  hashes:
    binhash: c4055b30837558ccd38f512e4aad46ef
    md5: 56e0394d389b458cb0958af20fde4925
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/coupler/a2i.nc
  hashes:
    binhash: 48470fb482ee7daa488b04477997b604
    md5: 2ea577c6b8ae1d121313f227e00a2575
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/coupler/i2a.nc
  hashes:
    binhash: 7a1011b89ade4bbb24feee1efd205730
    md5: 072977f410d91505498d54aa10dfbd8e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/coupler/o2i.nc
  hashes:
    binhash: d98d9bc583e2ee9a4452f85383794b7c
    md5: a064a98f4315e4bcf755219a3f19db50
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/cice_in.nml
  hashes:
    binhash: b51f1e81d03940dc173cb7e9c30c7884
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/ice.restart_file
  hashes:
    binhash: 03d3ca4e9c6782b89a5f07a6e35aa936
    md5: 4922bd352bf20ae5ca4246a9732a8114
work/ice/RESTART/iced.19790401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19790401
  hashes:
    binhash: 59c8a48752b86083b1207b6caacabb3e
    md5: db735022d183bfed335527d81896eb0a
work/ice/RESTART/iced.19790501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19790501
  hashes:
    binhash: 56e65a214eda9f61c80b11c73cf73fd8
    md5: 6674fe2db7d1c74bd64ec6631c9d2614
work/ice/RESTART/iced.19790601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19790601
  hashes:
    binhash: d653a5d2dae791b9ade47667446c911e
    md5: 6d1e283c0c7c2d29e611d6128a05170f
work/ice/RESTART/iced.19790701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19790701
  hashes:
    binhash: d70de26ba37e2436ce01fbd3e4b8bbf2
    md5: d6771f728ced332c8f6503286b3c0334
work/ice/RESTART/iced.19790801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19790801
  hashes:
    binhash: 3c8e2e02eaae628f55f88fc74c073a98
    md5: 3d001b7b0b480388edcac6ec9a6f08f9
work/ice/RESTART/iced.19790901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19790901
  hashes:
    binhash: 591ac85cf38151db731bc9a3a05dc5e5
    md5: 2d341e42c9afb113b68040c9870750c6
work/ice/RESTART/iced.19791001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19791001
  hashes:
    binhash: 1d5ee6262c6dd07969a036f40ad166d7
    md5: c69a8e5b14658910d513d3f6305177b5
work/ice/RESTART/iced.19791101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19791101
  hashes:
    binhash: 02d22b082b4cd6b32d93f5173b40ed9f
    md5: 0603800fecdd0701a3e85067f33ca3ff
work/ice/RESTART/iced.19791201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19791201
  hashes:
    binhash: b4ec74bb9b37bf6b8abb784ca46e8cde
    md5: 5d1bb9ee62591179f5a7c1d0171ff30f
work/ice/RESTART/iced.19800101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19800101
  hashes:
    binhash: e56473de48bc5838f94f131c243c5a87
    md5: f239f0842bb42c11c2fc317d5dae26aa
work/ice/RESTART/iced.19800201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/iced.19800201
  hashes:
    binhash: 9cf5bc541516b66ff42f269288c31cd5
    md5: 19a8106e62b7e6daa83baee7e1b06d06
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/input_ice.nml
  hashes:
    binhash: 293825001a82f12af278ad17ac79f7af
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/mice.nc
  hashes:
    binhash: e71c2ecf4977446086ea73c27e43fe52
    md5: 80aefe5432464098c33d2946b77ee3fa
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ice/reset.iced.850
  hashes:
    binhash: cf8c06a812179f4dc4650ef201317d5d
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 270805ec2b7215bcff9955bdc89f6bdf
    md5: fcda34e4454e71828205aa18c02c43d5
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 99243d4040f1f9d356512e101cf37df1
    md5: fff68287975e46a42ac178c3767199d3
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_age.res.nc
  hashes:
    binhash: 16be94125fd949a0ba3438e244ec04a2
    md5: 4027ad85e24fb89304667dccda4fc377
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 015eb5e0bf6ece6b7563b5e9d3637f1e
    md5: 01a6986f8104301cef631c9c3f13cc5d
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: c8e5cb93182667bebf7cee68924068ff
    md5: 6fb1b59a58c5765a844eab347387f0b2
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_density.res.nc
  hashes:
    binhash: f6c2b133145e1ce933022a3a791a49ea
    md5: e125c42fc0d91d698869abb037f686a7
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 603ee1460348757515bb6d303c609545
    md5: 99778be1c642cfccb9b89a9130903301
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 490cb6086758b0c3df9158acd0130169
    md5: 78a0b7cffc052747eb0b30cc34a603e5
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 019c4c542f85023f4f24865f6272f242
    md5: 044bb35ee9fc89ee4528e003a9a03470
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7df9819ee5acb25461e07e316b47a567
    md5: 3817c17161a1dd56d1e04d38ebbc7881
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 738dc177136744aeb50dbfe8f449d00f
    md5: d0300a970b6bf044b5a1e8eced02f9fc
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bee440d47a7ebfaa3ab53cecc39fb810
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_solo.res
  hashes:
    binhash: f3c3db86d54964b44ced8dcfeb0d480c
    md5: 15ff73039e3aa3cfff58a5988204a62f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 09e2a1fdc8f06cc039a4d71d321507cc
    md5: cdd789f4c5782219e3f50f1296babf4d
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 5c320120b12dc68c170c8ab121afb8d3
    md5: b98a4a6a1db4ea5fc82c6891e5ace357
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_tracer.res
  hashes:
    binhash: 2f25c6fe77bd888fdfadea2ce1020b01
    md5: 7dbf3838686adf07d300d4fafc4c7a4d
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_velocity.res.nc
  hashes:
    binhash: b03c7d6f4dc77d50c78737c200170652
    md5: e35e77eb8caf228fe827264df1a41971
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart852/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: bad7f7d4b952ee02b250baf4db7676b2
    md5: 4ab4efacfbb717996d1cdf93d94ab272
