format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/atmosphere/restart_dump.astart
  hashes:
    binhash: 96e9f96a46ca764004d50eb9111ab308
    md5: 729fa4cf822d0968b83d774fd12a686a
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/atmosphere/um.res.yaml
  hashes:
    binhash: a13c7e15e1d215ae6f8672c6d3e9e1ea
    md5: 56e0394d389b458cb0958af20fde4925
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/coupler/a2i.nc
  hashes:
    binhash: 38aaf8a857017d80340ae3c37f28134e
    md5: c60c22fac21f70d3c82f494c39196207
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/coupler/i2a.nc
  hashes:
    binhash: eb4de7858ec15cd5b4f67e298297877e
    md5: 8ef7d11f994b405cd77d680c699c9a37
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/coupler/o2i.nc
  hashes:
    binhash: 8d41c6f12d59aebd7e2f094aed788a07
    md5: 358e38beb90be126a73a9732c3668815
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/cice_in.nml
  hashes:
    binhash: f943e416dd39e594cac93b34cb9b9be3
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/ice.restart_file
  hashes:
    binhash: 0d980d6ae77b44a2fec3c7e1c23de23a
    md5: 4922bd352bf20ae5ca4246a9732a8114
work/ice/RESTART/iced.19760401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19760401
  hashes:
    binhash: a2cb3ca2d50de244289777290716ae00
    md5: 9eb660cb8eb003cf75d9643b8f802b59
work/ice/RESTART/iced.19760501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19760501
  hashes:
    binhash: ea37d1392c55df169f9622157d0ac140
    md5: aab9a73e2a7b47a144cae83305dd5c8e
work/ice/RESTART/iced.19760601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19760601
  hashes:
    binhash: 7dbcc375baea4aef0e4f7c39000095cc
    md5: 8532afc2b7c763e27992bb0622d30a2f
work/ice/RESTART/iced.19760701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19760701
  hashes:
    binhash: ed5ae1bc32681dadcaad573aeb45a448
    md5: cb3957c90f46d80bdeffe95877ba8a82
work/ice/RESTART/iced.19760801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19760801
  hashes:
    binhash: cbc7f56d971b4a2a22630e2a2bd7a1d7
    md5: 12e795cf558c65276052e43c32216652
work/ice/RESTART/iced.19760901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19760901
  hashes:
    binhash: 44952d75bcad3f0cd4232aaaf24fa3ae
    md5: 877255d4cdc3783feb92c51dd6ede8fc
work/ice/RESTART/iced.19761001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19761001
  hashes:
    binhash: 4696044035de27034010dc44476934d8
    md5: 461b3b91408a687f79e2498ed98e0b9e
work/ice/RESTART/iced.19761101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19761101
  hashes:
    binhash: 8fcafbf070a9121e071b37a08420e22e
    md5: 4daeda656f109b030467b1d7e764968b
work/ice/RESTART/iced.19761201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19761201
  hashes:
    binhash: 52c551881f29d0562406041fa0d2c44c
    md5: ab5d4f3096e8c7274ba0361dae7ccf3c
work/ice/RESTART/iced.19770101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19770101
  hashes:
    binhash: 5170f71f9cb19bb23efa0475d38d5833
    md5: 889b8fe0601498bde8579af873801157
work/ice/RESTART/iced.19770201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19770201
  hashes:
    binhash: 83859946ce0d06cab665b2be39f29fad
    md5: aa16021736f46176ebf020b862ba82eb
work/ice/RESTART/iced.19770301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/iced.19770301
  hashes:
    binhash: 2362c3cb092baaf685532fc5ec321768
    md5: f2187b4de2411eafc702d1444aa4ad29
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/input_ice.nml
  hashes:
    binhash: 91a728add18af28f1e23923de7e9c44b
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/mice.nc
  hashes:
    binhash: 959d52bd39942e8279809cf1bdbd6f47
    md5: 860ff9a14a14ba918028afed0f01b408
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ice/reset.iced.850
  hashes:
    binhash: 6db31e5595e64dfeb60a5b268a7b7115
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 8de02c4fbb32774eb59b1600a14ab17a
    md5: db3eaa048589d3c726158dce60529a70
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 1b2bd4580045d75dfd455a0e8b7c204f
    md5: 4b3048abf19edd583d727743bceaff93
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_age.res.nc
  hashes:
    binhash: 356f573b80d31296d3161592449e9bf9
    md5: fec7dd8f4de22aef124ac9a46256927d
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 28c888e9f8d44ba7c2d261a7920c1cd6
    md5: 4a0517577a278bd288ca3e66d1a737f8
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3fd30eebf9ced8f7e8f72708a883c111
    md5: e729efb1eb4597e0060f50717617a168
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_density.res.nc
  hashes:
    binhash: 106c171388877407862aae551b9251c1
    md5: 10d24bdc373fdcfa9f6976f88bf7c01b
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_frazil.res.nc
  hashes:
    binhash: c68eef6e69f02402b887778fdc7b525b
    md5: 10f6447ff12db318207aa642566a4f26
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 7e91b34c68ea572b8b24a70e3b972f28
    md5: 8634818ee39f5b6b0884ffa0f5ef3f59
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5c24b9b89838821af7fd782bd3e49544
    md5: 6f3f0e6c5af337b2c5e37b694b2f08a6
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 617766288b683f3ebe0b16db7abac87b
    md5: d21d5f010cafe12ec942716e8589680e
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c05df6773f7a4bf2d770343089baa2b3
    md5: a94a86a9fe60bb5bb930babe3319c39c
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 86cdfc1c2c1a355ae9c1d48efa60b898
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_solo.res
  hashes:
    binhash: 2e72aebc43387ae67339521a42185803
    md5: 15ff73039e3aa3cfff58a5988204a62f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 64abd8282c11ec511ba4a1816eb1e634
    md5: e3be97f025d3714d623fbfa52f322f79
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_thickness.res.nc
  hashes:
    binhash: df5ce0b5d03ba71c74d10b7391b95a0b
    md5: e1713a469290dd4d23bd9d221af9b6cd
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_tracer.res
  hashes:
    binhash: dcba353351f473b61b8f202e81bb97a0
    md5: 727132eda178ca7d7f55eb2d494a1e63
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 88164e3d5b8d819b3627b02527399dcf
    md5: 4a2223aa0b22d2c4a50ce6dc84b38a5e
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1000/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 19f24579237d312ed737091fbc201edb
    md5: 76042cbd50784842dfa403b3ada49b45
