format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/atmosphere/restart_dump.astart
  hashes:
    binhash: cc75fc6a15c99d5f863486207d13fec9
    md5: 809c040337104abaa96181e1d119ce8d
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/atmosphere/um.res.yaml
  hashes:
    binhash: 5a681b4656dcdda5173de28f0efa3995
    md5: 56e0394d389b458cb0958af20fde4925
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/coupler/a2i.nc
  hashes:
    binhash: 862c318e73856a93d516a242c0692285
    md5: efdfbeda2b7c7d60c622598dccc49dba
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/coupler/i2a.nc
  hashes:
    binhash: 798a655a8d02e72b187914def05e40c2
    md5: 70d2360e495fc61b5492c96d0f130b55
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/coupler/o2i.nc
  hashes:
    binhash: 2f70e935c7ca827e1d85228e77522121
    md5: 59f068ae5e125edd8f528eee2d6f8589
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/cice_in.nml
  hashes:
    binhash: 4f2b15598f373a8eb031ed04af26f83f
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/ice.restart_file
  hashes:
    binhash: 122433c4bfd7d4b27d15451ab17e0e9a
    md5: 4922bd352bf20ae5ca4246a9732a8114
work/ice/RESTART/iced.19770401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19770401
  hashes:
    binhash: a2ae18ee01b9d27ef9445c913b44ea65
    md5: b1c863e230114bee8d33b2f792fbae98
work/ice/RESTART/iced.19770501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19770501
  hashes:
    binhash: c97e48a7b2ee2b6362d5c74f8d75bc6f
    md5: a71d7ff89eb8e3bc02881a8cf9e7d956
work/ice/RESTART/iced.19770601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19770601
  hashes:
    binhash: 0567156d4559b9262341cdbbbe2f575f
    md5: 9203ffd807b25e060f7c71352f07ebff
work/ice/RESTART/iced.19770701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19770701
  hashes:
    binhash: 526d87633028cdc1673b419fedfb7151
    md5: 9b5ded4b4052b19e823a94d883ee462a
work/ice/RESTART/iced.19770801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19770801
  hashes:
    binhash: c56faf9c576eb92a117a6731207a8fe5
    md5: 365015f301d439c9d58901136143b8e3
work/ice/RESTART/iced.19770901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19770901
  hashes:
    binhash: 6a2917c6eb631cb0b4d88edafde8b813
    md5: ba3198d407173cbbf323d4dce92387f2
work/ice/RESTART/iced.19771001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19771001
  hashes:
    binhash: 32e9755d336c2916cd8dff3f2cd4d262
    md5: 21e7217c879b0395f8b7940e2b512c92
work/ice/RESTART/iced.19771101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19771101
  hashes:
    binhash: e3e1879174ab5776d039673a96df3771
    md5: 2152cb8a74d81528cef9ca41aa4cf48a
work/ice/RESTART/iced.19771201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19771201
  hashes:
    binhash: e6320270a351c976c60d4aa396171254
    md5: afb96d6a74e3e08744e407bfe87cf8be
work/ice/RESTART/iced.19780101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19780101
  hashes:
    binhash: 6b480079442cbfb4cb6033124a393f0d
    md5: 776566a8ea9f38e919aa021c2d24d4d5
work/ice/RESTART/iced.19780201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19780201
  hashes:
    binhash: 3e32d2b01a343d3b86da5411af7b39e1
    md5: 7e47f140290041df4d4c0ed7d0ed11c1
work/ice/RESTART/iced.19780301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/iced.19780301
  hashes:
    binhash: d2eaa54e2679f8934867080591eecc9a
    md5: 1c4aec081d8076e00575f08a5426a2b7
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/input_ice.nml
  hashes:
    binhash: 9d593770a0ee12ca06a41a4f141b5cd4
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/mice.nc
  hashes:
    binhash: 400817231ae17f69fe79b3442fa8b1d5
    md5: 5c97c322033aed076ad2203f30164cb3
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ice/reset.iced.850
  hashes:
    binhash: 4bb6cd105075cea499ae4d86319cdc69
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 1ab58636db1ea22d1fc8c3c316ec5e8e
    md5: 58ea3bafd4b8c41606befbb8b99c000c
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 8ade70de09dcf2f83d2d91989c663a63
    md5: 7160fb23b97e56ef227aad1730119916
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_age.res.nc
  hashes:
    binhash: 4b3a2a74ec197fe565d6e7a231a1a7c3
    md5: 22b1074521020e6f98679eb6a9d6933c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: aacdc6926e1974b9075ebd9832c0708c
    md5: 1aeaf05248e5db8a5346ce989380871a
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 411b2785acd3fba53ef58033ef95b839
    md5: 4a79b57a666a68194b5c68d1d5a21b3c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_density.res.nc
  hashes:
    binhash: 73898a18e97175c6ff0652b27819bbf8
    md5: a87f531d05ba41361ebfdc0d219aa1ad
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_frazil.res.nc
  hashes:
    binhash: f292a18181b6ad92bd3816fe1f40c0a0
    md5: d25ac1d39f252aa27f6a4f30a79fb8be
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 6fa5a6e9c522b234bc3a3a996e5baabb
    md5: fc960864e1df8b964c38bbec446a20a1
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2b0ebbd53029881248353bd0a1a0cda2
    md5: d065386d72932aaee14eeae6010bb557
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f412d20bf93908d55dbe448e4cb51a7b
    md5: 57f4b7c468bb310c1b9f633f133b3686
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ffb0d534be86527029a2033219c61407
    md5: 7fa2e2c6fd90dfaeb7673e7e7f3cc3af
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 3a0de09ff67551a7d4a5b0a1bc907c1f
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_solo.res
  hashes:
    binhash: 9665ec4b0e884140d8bbf1e6470148c6
    md5: 15ff73039e3aa3cfff58a5988204a62f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8b7f1111a0964de8613ab6475a14ba2d
    md5: 4b47577a3007f3b1fc384d7221ef3b0e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_thickness.res.nc
  hashes:
    binhash: cda8d074d785e0c6453eb37fdccdc0d7
    md5: beccfab24cf4b6b086c8a9eedf5fbd19
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_tracer.res
  hashes:
    binhash: 069282805f502c8a1f0436ea4362e106
    md5: 5e1bbfe123bde5a734f9cd7f1bb80ede
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 07fb3b485162bdd99a5f7105d968dd0b
    md5: e8b3af9276b3beef28419357d1662810
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1001/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: dcf7d0740cb6769bea2860dfadfc682b
    md5: 50a4c006425fa2245a54c6925a27c66b
