format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/atmosphere/restart_dump.astart
  hashes:
    binhash: b138da9f1e59310ec9129b144aa0e04a
    md5: cf71c41b41e641f5c97268a1c83d8671
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/atmosphere/um.res.yaml
  hashes:
    binhash: 8e82d4e93036147e08afb8f5b50b776e
    md5: 56e0394d389b458cb0958af20fde4925
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/coupler/a2i.nc
  hashes:
    binhash: 7bf09c8496171f33c4dec827278156c4
    md5: 50d24e09b21fa5e0467490e3b674b099
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/coupler/i2a.nc
  hashes:
    binhash: 4a4f74af9a802fdcccae3fadf40be21d
    md5: 79c5adcf788ed56cee508f0ade7cd602
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/coupler/o2i.nc
  hashes:
    binhash: cc61a558c3116082dfb5c3a8044737ae
    md5: ca61ad96b31d20c18b5c53c701f5a8d2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/cice_in.nml
  hashes:
    binhash: b5f8515b9f88075c3751cdaf021dfdc8
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/ice.restart_file
  hashes:
    binhash: 986825fa89e07b1e108f3396ee779a64
    md5: 4922bd352bf20ae5ca4246a9732a8114
work/ice/RESTART/iced.19780401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19780401
  hashes:
    binhash: 2371840e5cb7c0d5c6e82f3fc1f9a90b
    md5: d796bc38f6e114c8a7b8974c0ecbebca
work/ice/RESTART/iced.19780501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19780501
  hashes:
    binhash: 38144401e56448cb9507722db6df9b96
    md5: 82c21a92ed92e71e92e284bf1fb5de49
work/ice/RESTART/iced.19780601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19780601
  hashes:
    binhash: 202ce1b92e45482c667dd7babe2718df
    md5: 2d60b7e56cd36e24e4cef43c64230e63
work/ice/RESTART/iced.19780701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19780701
  hashes:
    binhash: c67b9b196246cefe643554cd0044eac8
    md5: 20e3edb75f9e1c464ccc5d424d1413e6
work/ice/RESTART/iced.19780801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19780801
  hashes:
    binhash: 1a97a0c4c00709f20dc8f51caf69ef1a
    md5: 622e274544e26b513243865f7ce151a4
work/ice/RESTART/iced.19780901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19780901
  hashes:
    binhash: 9419beddca9f24a55d33fd73c53b34ab
    md5: 2965ec417e906e422c58665113e3dca5
work/ice/RESTART/iced.19781001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19781001
  hashes:
    binhash: 7e57cd56fb90b4cddb48cd917a7d8a5c
    md5: ab1a757159cffabb45b7957b8e9a5eef
work/ice/RESTART/iced.19781101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19781101
  hashes:
    binhash: 58c6feb14f3dcad49585c2155836c38b
    md5: af0e40310e0237a2fdd0c066f4a2e72c
work/ice/RESTART/iced.19781201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19781201
  hashes:
    binhash: 0777972f6b8096635061450e01fbff10
    md5: 3308e84d36131acb30151b34344282ba
work/ice/RESTART/iced.19790101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19790101
  hashes:
    binhash: e42478d4c605109c1d3757db4987ede5
    md5: b5cf62b49be787ddbca9997ffbe2c260
work/ice/RESTART/iced.19790201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19790201
  hashes:
    binhash: 8bf5946930ade5cb9564a7b4d33dbe90
    md5: 13d80eb226d0d97c76142061a5c5b4f3
work/ice/RESTART/iced.19790301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/iced.19790301
  hashes:
    binhash: 247eabf1d18b4ca15ca40f37e83fd14c
    md5: 61f36d629cc885b1cd8cb34155200cae
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/input_ice.nml
  hashes:
    binhash: 5c49c9b1f7d116a0b7d5f0a4fd210fa2
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/mice.nc
  hashes:
    binhash: 4281fb3ed8c6322c8b7de2d99f5d2adb
    md5: af722fc0854aa57600f3af5e236e62ac
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ice/reset.iced.850
  hashes:
    binhash: 4f473d7aa8460d09cb914703c7039796
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/csiro_bgc.res.nc
  hashes:
    binhash: ebbcb28aead3069b335e804925ae43eb
    md5: 87de7d45c8161f87943ba880a60ff6f3
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 4ff3b3bdfe5df20929f6d35697bef8fa
    md5: 922595b0e13c914150d9496c4b3aea8c
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_age.res.nc
  hashes:
    binhash: c6cb5409fb59ef9cdc6b3a27f6001193
    md5: 3a58f407be796807487ab37e7410bc9b
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e805eca82d21fdfa6e8b4286abd7b5a8
    md5: 6aad9f09683d556535c135d6f80ea589
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: eb7dd63c53c6e25f1cf58a30de891200
    md5: d17fdf70261bc69a6711cba95d1daa42
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_density.res.nc
  hashes:
    binhash: afba0e60a7d3f381f99b1357b2e34b56
    md5: 298054fd679f17dabbd0bd97e2e0523c
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 4c186434d09ca87eaafe3010a8f1c6ab
    md5: bfc7620925ba00e3e194c8ef6423ca39
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 2d8a14d0b0a1f1e56a78d28604220e3b
    md5: 2b9ed8bcf49d95825904faebb2e64b92
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 50bb5245ca92192c00b3eb1adc9960dc
    md5: ea2de047c30eea014456f73ae38a0afe
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e630d5a7224bc3f4e4abba6d5dc3406f
    md5: 94b872b8ffeae22ff2195763755ae704
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 50f1cfa24a0e03d458d2041c09e59443
    md5: 31f0c6dfa8e3379ba50d7fa17f253192
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: d39a21b18d1eff0ab8bafe88a44b6f23
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_solo.res
  hashes:
    binhash: f6adbad7d80f7ea163e54e6cbe346f85
    md5: 15ff73039e3aa3cfff58a5988204a62f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: c303ee1951190d1690f9aac404bc95f2
    md5: 85bbfda53ffecaab9bb68467f8c9356c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 431b547ca6a34d4f0aceb445f6791d42
    md5: a68b0e20274295584780093ac8f5009a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_tracer.res
  hashes:
    binhash: 4e9b65f4042406a8e6b602075eb8b533
    md5: f812b880774d27d46b3d8d6dc95b0221
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 09b138c7d4eabe0e0c3b50e86492171e
    md5: 11eb18d69f5ff01c96b2f2e668646881
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart851/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 859ce854240c720b6a6f570b081a8236
    md5: 538b8c7233cd5231e4b145550cf6171c
