format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/atmosphere/restart_dump.astart
  hashes:
    binhash: ec33b480e0bd3a39c2ddc35c50e4405d
    md5: cac804246200972683694a02f1182985
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/atmosphere/um.res.yaml
  hashes:
    binhash: 03daa29a2c039f8d886995c453c7e5fc
    md5: 56e0394d389b458cb0958af20fde4925
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/coupler/a2i.nc
  hashes:
    binhash: c0f2996bdcb6c7c6efb6681f607a0a2e
    md5: 2d1810d154b6ae340f72b9103fa2cf56
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/coupler/i2a.nc
  hashes:
    binhash: 1fe58befaaeb7bac6979a83a81f0ce2e
    md5: 7a1940185d914f5bce4fd96789257ed1
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/coupler/o2i.nc
  hashes:
    binhash: b854203117ed681bd0f1a619a23e768d
    md5: 40ce5198e6bc069077c16a7d8bf7aea2
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/cice_in.nml
  hashes:
    binhash: 1bb6a794b2953d0d1611b7500ee477c1
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/ice.restart_file
  hashes:
    binhash: c8874da301af84cd85b61f00933aa696
    md5: 4922bd352bf20ae5ca4246a9732a8114
work/ice/RESTART/iced.19780401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19780401
  hashes:
    binhash: 1db7c79c7cff47e32ab5f5d4849cc81d
    md5: c53421937c9b9ca37e287129ba64056e
work/ice/RESTART/iced.19780501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19780501
  hashes:
    binhash: d82ae30990db7b50e109c3f7448b9bc6
    md5: 7b77089237d3df4e7b23a6e24b7bd7ac
work/ice/RESTART/iced.19780601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19780601
  hashes:
    binhash: acf39315ecf575cda67c2ed69ad79233
    md5: 1b9205e4b2bcc2f9c6019e8cefd2d7e8
work/ice/RESTART/iced.19780701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19780701
  hashes:
    binhash: e87322a6d9425504f71199abf1de10d3
    md5: 3b0dad2bcc4620b6155c9402adb60f26
work/ice/RESTART/iced.19780801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19780801
  hashes:
    binhash: 508608e962e0a6727ebab0ccedb8f9fa
    md5: 117484e53004dd7a1b5627a6339023d7
work/ice/RESTART/iced.19780901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19780901
  hashes:
    binhash: 6f3900c684fde1fe7a32dcb28fb78d69
    md5: 82c2f5c76118c5bba63b96761617f968
work/ice/RESTART/iced.19781001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19781001
  hashes:
    binhash: 26ad746d016fb63366fb04853e816ddc
    md5: 865759ff11196884f8566080818cb590
work/ice/RESTART/iced.19781101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19781101
  hashes:
    binhash: 10c0883fa19c4cb056ca195af0ed3f00
    md5: 85ec37181ae6c416761fa995b7ea0775
work/ice/RESTART/iced.19781201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19781201
  hashes:
    binhash: 348d91fc36b3fe7ba6c85fa05f5f4017
    md5: b69437c39571216c717aeea6d15bdd5e
work/ice/RESTART/iced.19790101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19790101
  hashes:
    binhash: e6273e772d80bfc814e93a9d16c28c45
    md5: b65a7dc0e77865b78371eb4c75e683c3
work/ice/RESTART/iced.19790201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19790201
  hashes:
    binhash: 2aebe13fbd9a569c90e2dfc0aa19d714
    md5: 6508c06033bbf3f98d789b1f915e3e73
work/ice/RESTART/iced.19790301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/iced.19790301
  hashes:
    binhash: ecd97f817c1b6326d8ab56653b4c577c
    md5: 52978c5df73fc836f65964728ee496c2
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/input_ice.nml
  hashes:
    binhash: 36b1dd81a869202c66c721022dff6518
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/mice.nc
  hashes:
    binhash: eaa543e9d796c5a6deaebd04795719af
    md5: c233913f3e7c2ef268b59ee5c15dba59
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ice/reset.iced.850
  hashes:
    binhash: a657740ed710aee47b0f94608064a724
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/csiro_bgc.res.nc
  hashes:
    binhash: c776d11dade6eae3b2a76fa0a674ec7c
    md5: 4bc142b5027c77753a1c04ea16589030
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 7990dde8400e30b76a81cae73db6e8aa
    md5: 94128f7b54cb9846c2d900dcad9f90c2
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_age.res.nc
  hashes:
    binhash: 7d75f75ed74a65c6b839a4dd7ec7b53e
    md5: d6a51b916f41fc0632140584c97f6ad9
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 99ee89056cb280afbaeabb6df01a1b62
    md5: 22b694eda27724c892c7a140ec143133
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: e44f5e8999190adb762b10f8faf727c1
    md5: 52ef6545e5183b0bb1637f3b7a11e868
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_density.res.nc
  hashes:
    binhash: 696f326432470b3a04243ebd4bf054e8
    md5: 17d89b73c7bac0807f5d1382ad493f83
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 2bcaa4e346b2a44564fbed6a92bb1a23
    md5: bbc04ef763ac056e2d7b1cee15a5affa
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: f24f85231600e526a5acabc1ffb9827f
    md5: 48256e432006e0698b68a3a2055d1730
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_neutral.res.nc
  hashes:
    binhash: ffeedc4f7234d54f93aaeb7334b013ea
    md5: de7511f66ec2010b5fa6d70a3b5b4217
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 43ac2869ddf06b2ab3e542d99e47cd9a
    md5: 07ff09dcac659677c6cad32bc6a24ae2
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 2c07c56a43aaef0226e2a6b277bd5566
    md5: 2c26edecd7e24984d32b94c4670c40c3
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: c6caa3c29e3c7de9bb1cb36f26a3ee03
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_solo.res
  hashes:
    binhash: e822f6518d98cf83c2d319c028430a2d
    md5: 15ff73039e3aa3cfff58a5988204a62f
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: fa194dc3138f2de5efee11bc53a57865
    md5: 6970d61a049d35b7de9aece0ef67055f
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 444a0427576552d0372f3490cba1d282
    md5: 192d5fc27ff731fa0f93456a29a1d86a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_tracer.res
  hashes:
    binhash: 5a9f6ca9698bd63bb14cc439c40aee03
    md5: e4eebbc3587d4db3ac0d005196a29169
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9d3b6967fdaae84ef2949862c6ef05c0
    md5: 2c5cd8181778b23c81fe5b08a4bf533f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1002/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 2362c9be8b00d438234b5462828e1706
    md5: 54a47b25549e8f51e9c05db46b54eb50
