format: yamanifest
version: 1.0
---
work/atmosphere/land_frac_0851.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/atmosphere/land_frac_0851.nc
  hashes:
    binhash: 8385558c54fcf125de049560ea5e90e0
    md5: d83342afb4c53236df0ab871ab193664
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/atmosphere/restart_dump.astart
  hashes:
    binhash: 2b8418f2aa349bf7019b91a99e9cbb73
    md5: eeb8196b3feab638a9a3a31e4bb09215
work/atmosphere/restart_dump.orig:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/atmosphere/restart_dump.orig
  hashes:
    binhash: d17ed0a7e8bfa2711cb3d47bfb86f990
    md5: 2a1c8f494d51523bc658862d97cd95c2
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/atmosphere/um.res.yaml
  hashes:
    binhash: 368cc7d6cfde338e3620420aa2cb0a0c
    md5: e785058bad1cd1704b4058f4052c6565
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/coupler/a2i.nc
  hashes:
    binhash: af0d3ba3ed9b3c629b8b83df4a0d93eb
    md5: 84f86bcfabe068e555ab3707ff8a68c4
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/coupler/i2a.nc
  hashes:
    binhash: 8ebe322a15e37b19f110ef7faa5a9843
    md5: e5b84138d52012e312142c42e54675fc
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/coupler/o2i.nc
  hashes:
    binhash: 969f03cf656e46b01dc97352a88c902f
    md5: 71eb6a08383138c01f8602b35d57450c
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/cice_in.nml
  hashes:
    binhash: 3e64ab9258e9a47ba886474271f556da
    md5: 167ce626f087671968b5f76d2aea3a6c
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/ice.restart_file
  hashes:
    binhash: 113644569cb8d1c93e867ff8c95d2941
    md5: 761dc0cdcb3a9a2177d2d039f35323bc
work/ice/RESTART/iced.19770401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19770401
  hashes:
    binhash: ca379d2ad3b174d77762fbe6bb42c377
    md5: fc95de8cf437b2b6d0aa67a7e607f5f6
work/ice/RESTART/iced.19770501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19770501
  hashes:
    binhash: c87b5b79640d7e594fa97d7d54d7da9a
    md5: 6d13142dd250c19c6b8244e7af6ee554
work/ice/RESTART/iced.19770601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19770601
  hashes:
    binhash: bcaf1ef691849e74853d57f6878616ba
    md5: 5c492a0565bcf255bb93a672a9ea5b84
work/ice/RESTART/iced.19770701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19770701
  hashes:
    binhash: 51dfb45d6ed0bd92561bb067a4af9cac
    md5: 19cf0e38f7acf213f8b84e9360748909
work/ice/RESTART/iced.19770801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19770801
  hashes:
    binhash: e1efa0ae447126b9463726c7b4d8194c
    md5: 6450a6c8f08e271834609d5db95343dd
work/ice/RESTART/iced.19770901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19770901
  hashes:
    binhash: 12c001709a0e5905aac308fd53544c0f
    md5: c98f9cf2c88051b7996b7d168ad3910e
work/ice/RESTART/iced.19771001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19771001
  hashes:
    binhash: 9514ecb8cfd6309914058576c4c3b610
    md5: 5a7ccfc0a6d006abe4f75b116a87ef39
work/ice/RESTART/iced.19771101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19771101
  hashes:
    binhash: a8031adad659f82339a5686420184fc6
    md5: e5fa1657e1c347ac27c43a3af42bf2c8
work/ice/RESTART/iced.19771201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19771201
  hashes:
    binhash: 5bd7d86016da8c420eacad84c35d51b6
    md5: 6f8b95925213a340b91e8ebd30100558
work/ice/RESTART/iced.19780101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19780101
  hashes:
    binhash: eb613e306b54beb6610847815c62a09b
    md5: 926d6d2b41b14fa5352c03bf07bd7013
work/ice/RESTART/iced.19780201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19780201
  hashes:
    binhash: f6de31eadbb2c8b2f57399e596e59763
    md5: d4eb39746ed5270e1d471a47e4d1e2c4
work/ice/RESTART/iced.19780301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/iced.19780301
  hashes:
    binhash: 2542cc26287ff92266064f90c3760e3e
    md5: 99e0df1b4a446c1c6f85243c6210392a
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/input_ice.nml
  hashes:
    binhash: 64e7f81c58ee15fcdb5f67edf7cca836
    md5: 6b97b71356c286defad0d099d7475e34
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/mice.nc
  hashes:
    binhash: 911e4eda24a6cc9ca3e1e5cc0687279e
    md5: 27e191e8b30c0220be711d6630a5417e
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ice/reset.iced.850
  hashes:
    binhash: 09cebcf1e9dc2fe1cd6b955a7ebf43b9
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 0b4f8f8f61c89a7c6cd7cfb00073354b
    md5: 0a35cf11dd2fba46c1669589bed0f973
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: fac95ff3da78179bd71c70bc191bce36
    md5: 262ad6b2a5eeb6a1a384bb25a5e41f81
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_age.res.nc
  hashes:
    binhash: 0a5de0f25a59add7be18fff19528a309
    md5: a54dfbf65a1899979df76674a1193b00
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: d1688190ea6098a2592e5e8cb02a4ca4
    md5: 64a6c703d2b94b2973b479547bce14fa
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 629e1986a318d8b44b27ebcf318762aa
    md5: 7909928d90ba21625a128cc6b2c154c3
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_density.res.nc
  hashes:
    binhash: 39a33a632491542a7bd1acaa795bf43b
    md5: 2e3fe709335fbd17c3833b5284452217
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 59c745a7369535691fb582bf2959303e
    md5: 688da5c6ce62c14666fe3467a8e5e36a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 83633964166cd4fdfa4b17d87848e0da
    md5: 8d049db084e7f07328955ca1f34b7529
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 48c412e41de7169e2d54eed25b05bc0d
    md5: 32f2afcd7eab5d56c779e3f314d5aff4
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cca8a1b9ba028ec79007a54ae9e1746d
    md5: d962ab88cb56f44c21cbadc4274df202
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8a6a538813b97b8850e164933445caf4
    md5: 1837004727a02c3871a34dc254c89c01
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: bc5ef5715162d2b1ee33d7fa10da4b7f
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_solo.res
  hashes:
    binhash: 65c97d799fde1fcf9500efbd88520532
    md5: 85f39abd7f0a5f0162e804bd946190e8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e41fdd3d9d20a801ec3eaeb9c1248b89
    md5: fcee6b0d99d16f03c82c5b502458ea4e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 706e71c0d42d5ed50a542eba9f5c64c1
    md5: d778dd7eb1b6c9513965c86bfc3e0d65
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_tracer.res
  hashes:
    binhash: aa9d202a95b247b95898819b85926aa6
    md5: 3242445b7b3fa3028d80c00f22961b5f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_velocity.res.nc
  hashes:
    binhash: bf202e19438a0fd2498040e947656d68
    md5: 5b90c5ceaefc8823decb7e36cfc0212d
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart1861/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: fddf8aacba17a8a37d6c95f44022dd47
    md5: cb59130c21d3c53b377f84db463df91f
