format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/atmosphere/restart_dump.astart
  hashes:
    binhash: d69142302edf5094a9c04561688736fc
    md5: 649983e01d3dc12b41e5ccd6f788461e
work/atmosphere/um.res.yaml:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/atmosphere/um.res.yaml
  hashes:
    binhash: e8b27b0bbb7df4d613ab79b99a1e5990
    md5: e785058bad1cd1704b4058f4052c6565
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/coupler/a2i.nc
  hashes:
    binhash: 6f9d79bc9b394e677c16c35343962c33
    md5: 521c46b1257d9e8ca99bf767c0c901ff
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/coupler/i2a.nc
  hashes:
    binhash: 7df69b7c82b1d89878eac2ca52857b46
    md5: 283ee0c038d0fefc91dbfa92f051834e
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/coupler/o2i.nc
  hashes:
    binhash: 6a30b792cb6099de741e18c563253f3d
    md5: a8238a1741ae6f372db1ac9d6ec23ce4
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/cice_in.nml
  hashes:
    binhash: 33703605e0f71c25d03b6762d58cb950
    md5: 167ce626f087671968b5f76d2aea3a6c
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/ice.restart_file
  hashes:
    binhash: efde0d01e7e259a38f8effe953f67fcc
    md5: c5c62ed251b84c94d741c8f0bd0dc2f8
work/ice/RESTART/iced.19800301:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19800301
  hashes:
    binhash: 374a22f334001d76c1651b54e941fdcb
    md5: a16059262c27ac9df0e5bef602a7850b
work/ice/RESTART/iced.19800401:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19800401
  hashes:
    binhash: aabb62f44832f19e8f83f1a64a24a4f3
    md5: 3d53e6d803489a5523e6e82020bf7289
work/ice/RESTART/iced.19800501:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19800501
  hashes:
    binhash: 29112588f7fbfcb1bedc61596fc033cc
    md5: 4563edaf7e7a8019b6f7273246ad579c
work/ice/RESTART/iced.19800601:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19800601
  hashes:
    binhash: b4cb13276ea1bd628bdd55f68dea408e
    md5: 42ee6f4a631a803d69cee8aee109f231
work/ice/RESTART/iced.19800701:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19800701
  hashes:
    binhash: 940c49062b5401bf71b6c84ee07f696c
    md5: 7640a1635024e56cdb1556e0fdae35e8
work/ice/RESTART/iced.19800801:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19800801
  hashes:
    binhash: 5b041da804eb969aa1f42d2fc3d25f31
    md5: a39b2d21faaf2fa250624efdddc6ca1c
work/ice/RESTART/iced.19800901:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19800901
  hashes:
    binhash: 0c83184b380fbe746a4a2558eb52a015
    md5: 477dd317435358ead81f6a5a03ccc486
work/ice/RESTART/iced.19801001:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19801001
  hashes:
    binhash: 8d249ddb6d89a507cf2d6377993ba683
    md5: 074632b0dc13ec53180fc27b40839efd
work/ice/RESTART/iced.19801101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19801101
  hashes:
    binhash: 64e0625e52e8cb5b4860463686c4338f
    md5: 576ca501b1ceace8ac61b62c70f96d7e
work/ice/RESTART/iced.19801201:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19801201
  hashes:
    binhash: 37ef22a3a744e7fc5956e8e1b5f07e4b
    md5: 710dedb56ab3d8c6d4bdcf503e36a346
work/ice/RESTART/iced.19810101:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/iced.19810101
  hashes:
    binhash: 55d7d820d62836009ec744b762d3986b
    md5: 87c676be71f9b6af762daff046de570f
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/input_ice.nml
  hashes:
    binhash: cac8c2bb828b4f867a7de150e79a568c
    md5: d591494e7b97330b772ae5718891769b
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/mice.nc
  hashes:
    binhash: dbcb2447a9b6cc9a1acda827f02f80a5
    md5: f5c1ea20c3dcf43fedf82909b38cbe25
work/ice/RESTART/reset.iced.850:
  copy: true
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ice/reset.iced.850
  hashes:
    binhash: 9dc4f47ea56178e9d2d4f0d6980ce232
    md5: eb0d009f05caf99492d40275a2ad15ca
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 5387fdafd3cb97b461ae5771b1b5b4cb
    md5: 850fdaa58c534d1c76ddd728ba3a9db3
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 452e4f5f887ca5f444d6a9a461997cd4
    md5: e08c4b36d0ce7d6d05930caba0b43a1f
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_age.res.nc
  hashes:
    binhash: 53bacd5544fc972bb17f8efa8db18f11
    md5: f6aa61b224d096c5ea31909ec470d188
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ddcc022e33500508969d43d075fa9c7d
    md5: 1e44b2b252eb3d75d2b8f18fb44571c2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 45274d9a99f84a78655a429e9393c663
    md5: 096890dd50f4331105a5e5e9b78594b9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_density.res.nc
  hashes:
    binhash: af5666a3347ad9f96488810f743c0a4a
    md5: d7c16bd723aef90b68edd91016cce3b0
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 09dac192684586f6c599d2f115007ae9
    md5: f18016b4ae29d46fe941600f3a090490
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: b6ee9dbd71aaacd69eb6f42d0731e1ce
    md5: 96d9907b62d156b9585c2a57264b1e87
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 57936500f412466b1cd721fa65163e6c
    md5: 4616b3033f25a3bd6b503e7d2e6ff1dc
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: e95b42fb6ae1e2b5edc487b1319db842
    md5: 7e028dbfdb48c673e7499d6aebe17cac
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 8cf1059ff8b424d91569386cb7950bed
    md5: 77af7fc2ef4a829c5eb92f62a24d187a
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: a2a91873e919d0434d7628a2ed682e95
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_solo.res
  hashes:
    binhash: 7652559b8df3ce7dc88799522f6dfe81
    md5: 85f39abd7f0a5f0162e804bd946190e8
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 0d04272fff7a767016a3fd50bd0a4106
    md5: a0a170ff99ff20132cd3e566b3a90b8e
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_thickness.res.nc
  hashes:
    binhash: ea8327766a44f3859449b61eae306b4e
    md5: c32f4808668b5cdecb8247dc04d8fc9a
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_tracer.res
  hashes:
    binhash: 24bf9e897440c58cffdd515822dab854
    md5: 093505ce7388f17447fe9dc55bc0e647
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c5e55d55e868a4791ae9dd7acac19bb9
    md5: 4b052740cff5878df0d50d8be13986d6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/w35/saw562/access-esm/archive/esm-pmip-last-mil/restart853/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: f2d7531cfa3484534ce73c9c0055edb8
    md5: 2244878059f5bebb445a47f306de3530
